### ISSUE TITLE
Cannot send email in bulk

### ISSUE THREAD

**Issue by botakist** [Nastoi/emailSMTP#4]
"Hi Mr Nastoi, how do I send email in to multiple users at the same time using your email SMTP?" Thank You!

**Comment by Nastoi** [comment]
Dear yong xin,

        Please do try to add these code into your project.

[cid:d14f0221-e869-4c4c-a619-52476889b6f7]


Best Of Luck
Nastoi



________________________________

**Comment by Nastoi** [comment]
[cid:bcdaacd7-0e60-4fa2-b828-fdd539d4d797]

________________________________
