### ISSUE TITLE
Send email to multiple user.

### ISSUE THREAD

**Issue by Riyah1295** [Nastoi/emailSMTP#5]
Dear Mr Nastoi,

I have integrated your source code with my project. It works like wonders when sending to a particular user. But how do I send to multiple user?

Thank you.

Regards,
Riyah

**Comment by Nastoi** [comment]
Dear syazriyah

         please do try add in these codes
[cid:30edb98c-e63b-49cf-b4f0-04488ed1bb1d]

Best Of Luck
Nastoi

________________________________

**Comment by Riyah1295** [comment]
Hi Mr Nastoi,

I'm unable to see the code.

Regards,
Riyah

**Comment by Nastoi** [comment]
[cid:b0c1681b-5135-46ca-8bef-8046d835dbfc]

________________________________
